### ISSUE TITLE
GitHub Repositories & Branches Issues

### ISSUE THREAD

**Issue by jfwu90** [engi-network/engi-blockchain-gql#184]
# GQL github repositories query for user returns incorrect list
Description: Repositories are repeated in the list returned. I uninstalled the GH app, reinstalled it, and went through enrollment in the callback URL.
Environment: Production and staging

Query:
```gql
query GithubRepositories {
  github {
    repositories {
      name
      fullName
      isPrivate
      owner {
        login
        avatarUrl
      }
    }
  }
}
```

Response:
```json
{
    "data": {
        "github": {
            "repositories": [
                {
                    "name": "demo-jest-design-matcher-nextjs",
                    "fullName": "jfwu90/demo-jest-design-matcher-nextjs",
                    "isPrivate": false,
                    "owner": {
                        "login": "jfwu90",
                        "avatarUrl": "https://avatars.githubusercontent.com/u/31193402?v=4"
                    }
                },
                {
                    "name": "demo-jest-design-matcher",
                    "fullName": "jfwu90/demo-jest-design-matcher",
                    "isPrivate": false,
                    "owner": {
                        "login": "jfwu90",
                        "avatarUrl": "https://avatars.githubusercontent.com/u/31193402?v=4"
                    }
                },
                {
                    "name": "demo-jest-design-matcher",
                    "fullName": "jfwu90/demo-jest-design-matcher",
                    "isPrivate": false,
                    "owner": {
                        "login": "jfwu90",
                        "avatarUrl": "https://avatars.githubusercontent.com/u/31193402?v=4"
                    }
                },
                {
                    "name": "demo-jest-design-matcher",
                    "fullName": "jfwu90/demo-jest-design-matcher",
                    "isPrivate": false,
                    "owner": {
                        "login": "jfwu90",
                        "avatarUrl": "https://avatars.githubusercontent.com/u/31193402?v=4"
                    }
                },
                {
                    "name": "demo-jest-design-matcher",
                    "fullName": "jfwu90/demo-jest-design-matcher",
                    "isPrivate": false,
                    "owner": {
                        "login": "jfwu90",
                        "avatarUrl": "https://avatars.githubusercontent.com/u/31193402?v=4"
                    }
                },
                {
                    "name": "demo-jest-design-matcher",
                    "fullName": "jfwu90/demo-jest-design-matcher",
                    "isPrivate": false,
                    "owner": {
                        "login": "jfwu90",
                        "avatarUrl": "https://avatars.githubusercontent.com/u/31193402?v=4"
                    }
                }
            ]
        }
    }
}
```

---

# Unable to get branches for repositories
Description: Can't load branch
Environment: Production and staging

Query:
```gql
query GithubRepositoryBranches($repositoryUrl: String!) {
  github {
    branches(repositoryUrl: $repositoryUrl)
  }
}
```

Response:
```json
{
    "errors": [
        {
            "message": "Error trying to resolve field \u0027branches\u0027.",
            "locations": [
                {
                    "line": 4,
                    "column": 15
                }
            ],
            "path": [
                "github",
                "branches"
            ],
            "extensions": {
                "code": "NOT_FOUND",
                "codes": [
                    "NOT_FOUND"
                ]
            }
        }
    ],
    "data": {
        "github": {
            "branches": null
        }
    }
}
```

# Unable to get commits for branch
Description: Can't fetch commits for a given branch
Environment: unsure

@garrettmaring is encountering this in prod, but I can't even reach this step because of the issue above.

Query:
```
query GithubBranchCommits($repositoryUrl: String!, $branch: String!) {
  github {
    commits(repositoryUrl: $repositoryUrl, branch: $branch) {
      sha
      message
      author
      committer
    }
  }
}
```

**Comment by garrettmaring** [comment]
Also, mentioning here that 'not found'/'error resolving' errors are generally not that the GQL query was wrong but rather that an internal error was propagated up. Would be great to keep the causing error instead and return that to the client.

**Comment by jfwu90** [comment]
@georgiosd 
User wallet ID: 5FLCw1SJBaBDpTGduFdYqonzf2Arsg1dYoaNMa3776w3nLDH
Repository URL: https://github.com/jfwu90/demo-jest-design-matcher

**Comment by georgiosd** [comment]
I only found one issue with the code relevant to the GH app integration and it only affected a scenario where the user would go and add repositories to their installation. See https://github.com/engi-network/engi-blockchain-gql/commit/bdb46b918c1913ea010dcb278d6b0e2719c73a3a. There was also a lingering reference with no impact, fixed in https://github.com/engi-network/engi-blockchain-gql/commit/f9d59fa7b463d970925dc13a791758fa9ac19981.

However, in passing I also found that the staging app was misconfigured, in that it did not request the appropriate permissions. I resolved this by copying the repository permissions requested by the prod app.

I believe that any remaining issues are relevant to the incorrect permissions mentioned above or https://github.com/engi-network/website/issues/205, or both.

I will test the get commits action above before closing the issue.

**Comment by georgiosd** [comment]
I did find an issue with the `github.commits` query when this is returned as `null` from the repository, this is fixed in https://github.com/engi-network/engi-blockchain-gql/commit/ed1ff87abce3e98db56f164bef6e04621148ba1c

I also opened issue https://github.com/engi-network/engi-blockchain-gql/issues/190 to enforce uniqueness of the `user <--> installation pair` but this shouldn't give any problems even as-is, for now.

If you face any more issues with this code please provide:
- Environment
- User (wallet or id)
- GH Installation ID from https://github.com/apps/engi-github-app-staging/installations (staging) or https://github.com/apps/engi-github-app/installations (prod)
- Repository URL and branch queried
